import type { NextPage } from "next";
import Head from "next/head";
import Search from "../components/Search";
import styles from "../styles/Home.module.css";

interface Props {}

const Home: NextPage<Props> = ({}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Github Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Github{" "}
          <a
            href="https://docs.github.com/en/rest/reference/search"
            target="_blank"
            rel="noreferrer">
            {" "}
            Search
          </a>
          !
        </h1>

        <Search />
      </main>
    </div>
  );
};

export default Home;
